---
title: ""
---

## Talks & Presentations

::: {.arrow-list}
* **Inferential Multiverse Meta-Analysis (PIMMA)** | [View Slides](slides/innsbruck_lesson_copy.html)

* **Cognitive Science Arena (CSA) - 2026** | [View Slides](slides/csa_2026_slides_copy.html)

* **Society for the Improvement of Psychological Science (SIPS) - Online Meeting 2026** | [View Slides](slides/slides_sips_2026_copy.html)

:::

<br>

## RStudio

::: {.arrow-list}
* [Introduction to RStudio & Data Analysis](teaching/intro_r_comunità.html)

* [Basic R Commands](teaching/comandi_base_rstudio.html)

:::


<br>

## Statistics

::: {.arrow-list}
* [Meta-Analysis in R](https://manentematteo.github.io/meta-analysis-summer-school-cagliari-2026/)

* [Mean | Sampling distribution](teaching/distribuzione_campionaria_media.html)

* [Standard Deviation, Variance and Mean Difference | Sampling Distributions](teaching/distribuzioni_campionarie_sd_diff.html)

:::

<br>

## Shinyapps

**Linear Models**

::: {.arrow-list}
* [Linearity Assumption](https://2j7s28-matteo-manente.shinyapps.io/lm-linearity-assumption/)

* [Homoscedasticity Assumption](https://2j7s28-matteo-manente.shinyapps.io/lm-homoscedasticity-assumption/)

* [Outlier vs Leverage](https://2j7s28-matteo-manente.shinyapps.io/lm-outlier-vs-leverage/)

:::

<br>

## Academic Writing


::: {.arrow-list}
* [Resources & Tutorials](materiali_scrittura_tesi.html)

:::





